### ISSUE TITLE
strange behaviour of doc vs class

### ISSUE THREAD

**Issue by tremblap** [flucoma/flucoma-docs#128]
after correcting the missing slash, we get a CI (and local) render that are consistent. The problem is that it seems to be adding elements to the class definition.

Best is to look at all the errors we get from FluidStandardize helpfile at the tip.

all these errors
```
WARNING: SCDoc: In /Users/pa/Documents/documents@hudd/research/projects/fluid corpus navigation/research/nightly_builds/SuperCollider/FluidCorpusManipulation/HelpSource/Classes/FluidStandardize.schelp
  Method -fitTransform has 3 args, but doc has 2 argument:: tags.
WARNING: SCDoc: In /Users/pa/Documents/documents@hudd/research/projects/fluid corpus navigation/research/nightly_builds/SuperCollider/FluidCorpusManipulation/HelpSource/Classes/FluidStandardize.schelp
  Method -fitTransform has arg named 'sourceDataSet', but doc has 'argument:: unamed_arg'.
WARNING: SCDoc: In /Users/pa/Documents/documents@hudd/research/projects/fluid corpus navigation/research/nightly_builds/SuperCollider/FluidCorpusManipulation/HelpSource/Classes/FluidStandardize.schelp
  Method -fitTransform has arg named 'destDataSet', but doc has 'argument:: action'.
WARNING: SCDoc: In /Users/pa/Documents/documents@hudd/research/projects/fluid corpus navigation/research/nightly_builds/SuperCollider/FluidCorpusManipulation/HelpSource/Classes/FluidStandardize.schelp
  Method -inverseTransform has 3 args, but doc has 2 argument:: tags.
WARNING: SCDoc: In /Users/pa/Documents/documents@hudd/research/projects/fluid corpus navigation/research/nightly_builds/SuperCollider/FluidCorpusManipulation/HelpSource/Classes/FluidStandardize.schelp
  Method -inverseTransform has arg named 'sourceDataSet', but doc has 'argument:: unamed_arg'.
WARNING: SCDoc: In /Users/pa/Documents/documents@hudd/research/projects/fluid corpus navigation/research/nightly_builds/SuperCollider/FluidCorpusManipulation/HelpSource/Classes/FluidStandardize.schelp
  Method -inverseTransform has arg named 'destDataSet', but doc has 'argument:: action'.
```

and these 2 strange entries
![Screenshot 2022-05-31 at 16 19 54](https://user-images.githubusercontent.com/10000381/171209872-878d6cf1-28bb-4d7e-8cef-0344493de93c.png)

**Comment by weefuzzy** [comment]
I suggest @tedmoore has a first look at this because I haven't prodded the sc template in a while and thought we had all this ironed out. But I do see that the rst has entries for `action`, which seems anomalous to me as only SC has actions: pretty sure the python or jinja was supposed to be adding the action stuff in, which might explain the extras?

**Comment by tedmoore** [comment]
i'll take a look. (yes, the rst should not have actions)

**Comment by weefuzzy** [comment]
Found it. Remarkably, the fact that the doc block for `inverseTransform` is indented by one (1) extra space screws up `docutils`' parsing and consequently corrupts the preceding block for `fitTransform`

**Comment by weefuzzy** [comment]
Fixed directly

**Comment by tedmoore** [comment]
Whoa. Is there a way that we can set things up to not fail when they're off by one space? (Maybe this is what you changed?) That seems very fragile.

**Comment by weefuzzy** [comment]
Not really automatically. Because rst places such significance on indents and whitespace, and because we don't see stuff until after `doctuils` has parsed it, I think the best we can do is what we're doing, which is validate exhaustively and issue diagnostics. 

As a reminder, the validation output is always logged to a file as well as the console (/flucoma-makeref.log), so it's definitely worth checking that over and confirming that it matches expectations, and bearing in mind that if something is screwy then it's probably down to indents or whitespace.

**Comment by tremblap** [comment]
we do get a lot of warnings of things not being defined... so maybe it is worth indeed looking at them - I sadly ignore most warnings since we get so many, sorry if I shouln't

**Comment by weefuzzy** [comment]
That's one reason for writing these ones to a special file, so that they can be scrutinised in isolation from any C++ warnings, which – yes – at times can just flood the console, especially given the enormous length of some of our type names. 

Probably a good plan for the C++ warnings is for devs to start using CMake presets with appropriately sensitive warning settings but to have the default behaviour to be quiet(er). I do periodically stomp through and try and resolve all the warnings on every OS, but it's a never ending job.

IAC, the take home for people working on docs is to make sure they use that log file!

**Comment by tedmoore** [comment]
> to make sure they use that log file!

That sounds good to me. At some point in the future I think it'll be good for the readme to point at all this. Especially since we'll be hoping others can help with maintenance.

**Comment by tedmoore** [comment]
Shall we close?

**Comment by weefuzzy** [comment]
Should probably generate and check new nightlies to confirm
