### ISSUE TITLE
SC Class definition files contain more than one Class

### ISSUE THREAD

**Issue by tedmoore** [flucoma/flucoma-docs#30]
For example the file FluidNormalize.sc has the class definition for both FluidNormalize and FluidNormalizeQuery.

The hiccup that this causes is that when I am going to the class definition files to pull the class and instance methods (and their order and arguments and arguments orders) my regex (🙄) finds the methods from these other classes as well. I could probably regex my way out of this as well (🙄) but I thought I would first check if these is necessary or just super convenient or possible to not do this way? 

I know SC as some concerns about what is in what files regarding inheritance. Is that related? 

Also, if you want to see this regex, check here: 
https://github.com/flucoma/flucoma-docs/blob/enhance/sc-update-yaml/script/SCJinja.py 
line 75

**Comment by weefuzzy** [comment]
I don't entirely follow why this is a problem, because I don't entirely follow what the script is for. There seems to be a certain amount of wheel reinvention going on there w/r/t the main flucoma-docs code that I'm currently refactoring in #24 to make SC doc gen easier. 

My main question is why do you need to parse a SC class file in python? The canonical information on message and parameter names comes from the generated docs. 

Can I suggest you just pause on this until I've finished my PR? It should make generating the first attempt at SC docs much simpler.

**Comment by tedmoore** [comment]
Totally.👍🏻

**Comment by weefuzzy** [comment]
Cheers. It's very nearly done; the actually hard stuff is finished, and now I'm just parcelling off host-specific behaviour in to 'driver' files, so it should be pretty obvious how to extend / mutate 🤞
